export const apiRoutes = {
  login: "login",
  change_password: "change/password",
  forget_password: "forgot/password",
  set_password: "reset/password",
  bureau: "bureau",
  user_master_csv_upload: "/user/upload/master-csv",
  employer: "employer",
  provider_plan: "provider-plan",
  provider: "provider",
  bulk_employer_uploader: "employer/bulk-upload-employer",
  employer_sample_csv_download: "employer/download/sample-file",
  dashboard_count: "dashboard/count",
  dashboard_records: "dashboard/records",
  dashboard_analysis: "dashboard/analysis",
  mapping_get_target_fields: "/get-target-fields",
};
